"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "ar" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ar")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage) {
      setLanguageState(savedLanguage)
      document.documentElement.lang = savedLanguage
      document.documentElement.dir = savedLanguage === "ar" ? "rtl" : "ltr"
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("language", lang)
    document.documentElement.lang = lang
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr"
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    // Common
    loading: "جاري التحميل...",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    add: "إضافة",
    submit: "إرسال",
    search: "بحث",
    filter: "تصفية",
    close: "إغلاق",
    confirm: "تأكيد",
    yes: "نعم",
    no: "لا",
    actions: "الإجراءات",
    view: "عرض",
    download: "تحميل",
    upload: "رفع",
    send: "إرسال",
    back: "رجوع",
    next: "التالي",
    previous: "السابق",
    select: "اختيار",
    selectAll: "تحديد الكل",
    clear: "مسح",
    reset: "إعادة تعيين",
    apply: "تطبيق",
    create: "إنشاء",
    update: "تحديث",
    remove: "إزالة",

    // Roles
    student: "طالب",
    supervisor: "مشرف",
    coordinator: "منسق",
    admin: "مدير",

    // Sidebar Navigation
    dashboard: "لوحة التحكم",
    myProject: "مشروعي",
    tasks: "المهام",
    meetings: "الاجتماعات",
    files: "الملفات",
    announcements: "الإعلانات",
    discussions: "المناقشات",
    messages: "الرسائل",
    grades: "الدرجات",
    notifications: "الإشعارات",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    profile: "الملف الشخصي",
    projects: "المشاريع",
    students: "الطلاب",
    supervisors: "المشرفين",
    reports: "التقارير",
    archive: "الأرشيف",
    assignSupervisors: "تعيين المشرفين",
    projectIdeas: "أفكار المشاريع",
    evaluations: "التقييمات",
    tasksAndEvaluation: "المهام والتقييم",

    // Platform
    platformTitle: "منصة المشاريع",
    graduationProjectsPlatform: "منصة مشاريع التخرج",
    mainMenu: "القائمة الرئيسية",
    mainNavDescription: "قائمة التنقل الرئيسية للوصول إلى جميع أقسام النظام",

    // Auth Pages
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    forgotPassword: "نسيت كلمة المرور؟",
    resetPassword: "إعادة تعيين كلمة المرور",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    name: "الاسم",
    phone: "رقم الهاتف",
    studentId: "الرقم الجامعي",
    employeeId: "الرقم الوظيفي",
    department: "القسم",
    role: "الدور",
    loginButton: "تسجيل الدخول",
    loggingIn: "جاري تسجيل الدخول...",
    createAccount: "إنشاء حساب",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    dontHaveAccount: "ليس لديك حساب؟",
    invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة",

    // Dashboard
    welcome: "مرحباً",
    welcomeBack: "مرحباً بعودتك",
    overviewText: "إليك نظرة عامة على مشروع التخرج الخاص بك",
    supervisorOverview: "نظرة عامة على المشاريع التي تشرف عليها",
    coordinatorOverview: "نظرة عامة على جميع المشاريع",
    totalTasks: "إجمالي المهام",
    completedTasks: "المهام المكتملة",
    upcomingMeetings: "الاجتماعات القادمة",
    projectProgress: "تقدم المشروع",
    recentTasks: "المهام الأخيرة",
    recentNotifications: "الإشعارات الأخيرة",
    latestUpdates: "آخر التحديثات",
    noTasksYet: "لا توجد مهام حالياً",
    noDataFound: "لم يتم العثور على بيانات المستخدم",
    errorLoadingData: "حدث خطأ أثناء تحميل البيانات",
    errorOccurred: "حدث خطأ",
    welcomeToplatform: "مرحباً بك في المنصة",
    startByAddingProject: "ابدأ بإضافة مشروعك ومتابعة المهام",

    // Project Page
    projectDetails: "تفاصيل مشروع التخرج الخاص بك",
    myProjectDetails: "تفاصيل مشروعي",
    submitProjectIdea: "تقديم فكرة مشروع",
    submittedProjectIdeas: "أفكار المشاريع المقدمة",
    projectIdeasStatus: "حالة أفكار المشاريع التي قدمتها",
    submissionDate: "تاريخ التقديم",
    approved: "مقبول",
    rejected: "مرفوض",
    underReview: "قيد المراجعة",
    noProjectAssigned: "لم يتم تعيين مشروع بعد",
    projectSubmittedUnderReview: "تم تقديم فكرة المشروع وهي قيد المراجعة. سيتم إشعارك بالقرار قريباً.",
    submitOrWait: "قدم فكرة مشروع أو انتظر تعيين مشروع من المنسق الأكاديمي",
    active: "نشط",
    completed: "مكتمل",
    pending: "معلق",
    inProgress: "قيد التنفيذ",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    expectedDeliveryDate: "تاريخ التسليم المتوقع",
    notSpecified: "غير محدد",
    tasksAndAssignments: "التسليمات والواجبات",
    discussionForum: "منتدى النقاش",
    evaluationsAndResults: "التقييمات والنتائج",
    supervisorInfo: "معلومات المشرف على المشروع",
    contactSupervisor: "التواصل مع المشرف",
    projectObjectives: "أهداف المشروع",
    noObjectivesYet: "لم يتم تحديد أهداف بعد",
    projectTitle: "عنوان المشروع",
    projectDescription: "وصف المشروع",
    projectStatus: "حالة المشروع",
    projectType: "نوع المشروع",

    // Tasks
    taskTitle: "عنوان المهمة",
    taskDescription: "وصف المهمة",
    taskStatus: "حالة المهمة",
    taskPriority: "أولوية المهمة",
    dueDate: "تاريخ الاستحقاق",
    assignedTo: "مسندة إلى",
    assignedBy: "مسندة من",
    new: "جديدة",
    high: "عالية",
    medium: "متوسطة",
    low: "منخفضة",
    urgent: "عاجل",
    addTask: "إضافة مهمة",
    editTask: "تعديل مهمة",
    deleteTask: "حذف مهمة",
    completeTask: "إكمال المهمة",
    markAsComplete: "تعيين كمكتملة",
    markAsIncomplete: "تعيين كغير مكتملة",

    // Meetings
    meetingTitle: "عنوان الاجتماع",
    meetingDescription: "وصف الاجتماع",
    meetingDate: "تاريخ الاجتماع",
    meetingTime: "وقت الاجتماع",
    meetingLocation: "موقع الاجتماع",
    meetingLink: "رابط الاجتماع",
    meetingStatus: "حالة الاجتماع",
    scheduled: "مجدول",
    canceled: "ملغي",
    addMeeting: "إضافة اجتماع",
    editMeeting: "تعديل اجتماع",
    deleteMeeting: "حذف اجتماع",
    joinMeeting: "الانضمام للاجتماع",
    scheduleMeeting: "جدولة اجتماع",
    noMeetingsYet: "لا توجد اجتماعات حالياً",
    upcomingMeeting: "اجتماع قادم",
    pastMeeting: "اجتماع سابق",
    requestMeeting: "طلب اجتماع",
    meetingNotes: "ملاحظات الاجتماع",
    date: "التاريخ",
    time: "الوقت",
    meetingRequests: "طلبات الاجتماع",
    submittedOn: "تم التقديم في",
    timeRange: "من 8 صباحاً إلى 8 مساءً",
    meetingsBetweenHours: "يجب أن تكون الاجتماعات بين 8 صباحاً و 8 مساءً",
    fieldRequired: "الرجاء ملء جميع الحقول المطلوبة",
    savedSuccessfully: "تم الحفظ بنجاح",
    errorMessage: "حدث خطأ، يرجى المحاولة مرة أخرى",

    // Archive
    restoreProject: "استرجاع المشروع",
    archived: "مؤرشف",
    archivedProjects: "المشاريع المؤرشفة",
    noArchivedProjects: "لا توجد مشاريع مؤرشفة",
    archivedProjectsDescription: "سيتم عرض المشاريع المؤرشفة هنا",
    projectRestoredSuccessfully: "تم استرجاع المشروع بنجاح",
    errorRestoringProject: "حدث خطأ أثناء استرجاع المشروع",

    // Projects
    allProjects: "جميع المشاريع",
    approveProjects: "الموافقة على المشاريع",
    addProject: "إضافة مشروع",
    editProject: "تعديل مشروع",
    deleteProject: "حذف مشروع",
    viewDetails: "عرض التفاصيل",
    projectProposalDetails: "تفاصيل المشروع المقترح",
    acceptProject: "قبول المشروع",
    rejectProject: "رفض المشروع",
    suspendProject: "تعليق المشروع",
    archiveProject: "أرشفة المشروع",
    projectApprovedSuccessfully: "تم قبول المشروع بنجاح",
    projectRejected: "تم رفض المشروع",
    projectSuspended: "تم تعليق المشروع",
    projectArchived: "تم أرشفة المشروع",
    errorApprovingProject: "حدث خطأ في قبول المشروع",
    errorRejectingProject: "حدث خطأ في رفض المشروع",
    errorSuspendingProject: "حدث خطأ في تعليق المشروع",
    errorArchivingProject: "حدث خطأ في أرشفة المشروع",
    projectAddedSuccessfully: "تم إضافة المشروع بنجاح",
    projectUpdatedSuccessfully: "تم تحديث المشروع بنجاح",
    projectDeletedSuccessfully: "تم حذف المشروع",
    errorAddingProject: "حدث خطأ أثناء إضافة المشروع",
    errorUpdatingProject: "حدث خطأ أثناء تحديث المشروع",
    errorDeletingProject: "حدث خطأ في حذف المشروع",
    errorLoadingProjects: "حدث خطأ في تحميل المشاريع",
    suspended: "معلق",
    progress: "التقدم",
    notAssigned: "غير معين",
    objectives: "الأهداف",
    confirmDelete: "هل أنت متأكد من حذف هذا المشروع؟",
    teamManagement: "إدارة الفريق",
    teamMembers: "أعضاء الفريق",
    addStudentToProject: "إضافة طالب للمشروع",
    removeStudent: "حذف الطالب",
    studentAddedSuccessfully: "تم إضافة الطالب إلى المشروع بنجاح",
    studentRemovedSuccessfully: "تم حذف الطالب من المشروع",
    studentAlreadyHasProject: "هذا الطالب لديه مشروع بالفعل",
    errorAddingStudent: "حدث خطأ أثناء إضافة الطالب",
    errorRemovingStudent: "حدث خطأ أثناء حذف الطالب",
    errorLoadingTeamMembers: "حدث خطأ في تحميل أعضاء الفريق",
    pleaseSelectStudent: "يرجى اختيار طالب",
    ideaDataLoaded: "تم تحميل بيانات الفكرة المقبولة، يرجى اختيار المشرف",
    errorLoadingIdeaData: "حدث خطأ في تحميل بيانات الفكرة",

    // Students
    studentsManagement: "إدارة الطلاب",
    assignSupervisorsDescription: "تعيين المشرفين للطلاب ومتابعة حالتهم",
    addNewStudent: "إضافة طالب جديد",
    totalStudents: "إجمالي الطلاب",
    studentsWithoutSupervisor: "طلاب بدون مشرف",
    studentsWithSupervisor: "طلاب مع مشرف",
    noStudentsYet: "لا يوجد طلاب حالياً",
    studentsWillAppearHere: "سيظهر الطلاب هنا بعد التسجيل",
    studentsList: "قائمة الطلاب",
    allRegisteredStudents: "جميع الطلاب المسجلين في النظام",
    assigned: "تم التعيين",
    withoutSupervisor: "بدون مشرف",
    changeSupervisor: "تغيير المشرف",
    assignSupervisor: "تعيين مشرف",
    selectAppropiateSupervisor: "اختر المشرف المناسب للطالب",
    selectedSupervisor: "المشرف المختار",
    currentStudentCount: "عدد الطلاب الحالي",
    supervisorAssignedSuccessfully: "تم تعيين المشرف بنجاح",
    errorAssigningSupervisor: "حدث خطأ أثناء تعيين المشرف",
    pleaseSelectSupervisor: "يرجى اختيار مشرف",
    fullName: "الاسم الكامل",
    enterFullName: "أدخل الاسم الكامل",
    enterEmail: "أدخل البريد الإلكتروني",
    enterPassword: "أدخل كلمة المرور",
    universityId: "الرقم الجامعي",
    example: "مثال",
    selectDepartment: "اختر القسم",
    noDepartmentsAvailable: "لا توجد أقسام متاحة",
    addDepartmentsFromSettings: "يرجى إضافة أقسام من صفحة إدارة الأقسام",
    selectedDepartment: "القسم المختار",
    phoneNumber: "رقم الهاتف",
    studentAddedSuccessfully: "تم إضافة الطالب بنجاح",
    emailAlreadyInUse: "البريد الإلكتروني مستخدم بالفعل",
    errorAddingStudentAccount: "حدث خطأ أثناء إضافة الطالب",
    assign: "تعيين",
    addStudent: "إضافة الطالب",
    enterStudentData: "أدخل بيانات الطالب لإنشاء حساب جديد",

    // Discussions
    discussionForum: "منتدى النقاش",
    shareIdeasWithTeam: "شارك الأفكار والأسئلة مع فريقك",
    newDiscussion: "نقاش جديد",
    createNewDiscussion: "إنشاء نقاش جديد",
    discussionTitle: "عنوان النقاش",
    enterDiscussionTitle: "أدخل عنوان النقاش",
    discussionContent: "محتوى النقاش",
    explainDiscussionInDetail: "اشرح موضوع النقاش بالتفصيل",
    tags: "الوسوم",
    optional: "اختياري",
    tagsExample: "مثال: تقني، تقرير، مراجعة (افصل بفاصلة)",
    separateTagsWithComma: "افصل بين الوسوم بفاصلة",
    createDiscussion: "إنشاء النقاش",
    discussionCreatedSuccessfully: "تم إنشاء النقاش بنجاح",
    errorCreatingDiscussion: "حدث خطأ أثناء إنشاء النقاش",
    errorFetchingDiscussions: "حدث خطأ أثناء تحميل النقاشات",
    all: "الكل",
    open: "مفتوح",
    closed: "مغلق",
    noDiscussions: "لا توجد نقاشات",
    noDiscussionsYet: "لم يتم إنشاء أي نقاشات بعد. ابدأ بإنشاء نقاش جديد.",
    pinned: "مثبت",
    reply: "رد",
    discussionNotFound: "النقاش غير موجود",
    noProject: "لا يوجد مشروع",
    mustBeInProjectForDiscussions: "يجب أن تكون مسجلاً في مشروع للمشاركة في المناقشات",
    mustBeInProjectToCreateDiscussion: "يجب أن يكون لديك مشروع لإنشاء نقاش",
    fewMinutesAgo: "منذ دقائق",
    hoursAgo: "منذ {hours} ساعة",
    oneDayAgo: "منذ يوم واحد",

    // Announcements
    announcements: "الإعلانات",
    announcementsManagement: "إدارة ونشر الإعلانات العامة لجميع المستخدمين",
    newAnnouncement: "إعلان جديد",
    publishNewAnnouncement: "نشر إعلان عام جديد",
    announcementTitle: "عنوان الإعلان",
    enterAnnouncementTitle: "أدخل عنوان الإعلان",
    announcementContent: "محتوى الإعلان",
    enterAnnouncementContent: "أدخل محتوى الإعلان",
    announcementScope: "نطاق الإعلان",
    selectAnnouncementScope: "اختر نطاق الإعلان",
    singleSemesterProjects: "المشاريع المسجلة في فصل دراسي واحد",
    twoSemestersProjects: "المشاريع الممتدة على فصلين دراسيين",
    other: "أخرى",
    selectTargetCategory: "حدد الفئة المستهدفة من الإعلان",
    pinAnnouncement: "تثبيت الإعلان",
    announcementWillAppearOnTop: "سيظهر الإعلان في أعلى القائمة",
    publishAnnouncement: "نشر الإعلان",
    announcementPublishedSuccessfully: "تم نشر الإعلان بنجاح",
    errorPublishingAnnouncement: "حدث خطأ أثناء نشر الإعلان",
    noAnnouncements: "لا توجد إعلانات",
    noAnnouncementsYet: "لم يتم نشر أي إعلانات بعد. ابدأ بنشر إعلان عام جديد.",
    confirmDeleteAnnouncement: "هل أنت متأكد من حذف هذا الإعلان؟",
    announcementDeletedSuccessfully: "تم حذف الإعلان بنجاح",
    errorDeletingAnnouncement: "حدث خطأ أثناء حذف الإعلان",
    unpin: "إلغاء التثبيت",
    pin: "تثبيت",
    unpinned: "تم إلغاء التثبيت",
    announcementPinned: "تم تثبيت الإعلان",

    // General
    fillAllRequiredFields: "يرجى ملء جميع الحقول المطلوبة",
    required: "مطلوب",

    // Common Actions
    total: "الإجمالي",
    noContent: "لا يوجد محتوى",
    viewAll: "عرض الكل",
    typeMessage: "اكتب رسالتك هنا...",
    attachedFiles: "الملفات المرفقة",
    attachFile: "يجب إرفاق ملف أو كتابة نص",
    feedback: "الملاحظات",

    // Task & Grading
    taskSubmitted: "تم التسليم",
    taskGraded: "تم التقييم",
    grade: "الدرجة",
    weight: "الوزن",
    maxGrade: "الدرجة الكاملة",
    evaluationFeedback: "ملاحظات التقييم",
    noGradesYet: "لا توجد تقييمات بعد",
    errorLoadingTasks: "حدث خطأ في تحميل المهام",
    userNotFound: "المستخدم غير موجود",
    newTaskAssigned: "مهمة جديدة",

    // Project & Students
    activeProjects: "المشاريع النشطة",
    projectsCount: "عدد المشاريع",
    noStudentsWithoutSupervisors: "لا يوجد طلاب بدون مشرفين",
    calendar: "التقويم",
    departments: "إدارة الأقسام",
    selectProject: "اختر المشروع",
    chooseProject: "اختيار المشروع",

    // UI Text
    noProjectsAvailable: "لا توجد مشاريع متاحة",

    // Archive
    selectProjectDescription: "اختر المشروع المؤرشف لاسترجاعه",

    // Supervisors
    addSupervisor: "إضافة مشرف",
    addNewSupervisor: "إضافة مشرف جديد",
    enterSupervisorData: "أدخل بيانات المشرف الأكاديمي",
    jobNumber: "الرقم الوظيفي",
    enterJobNumber: "أدخل الرقم الوظيفي",
    supervisorAddedSuccessfully: "تم إضافة المشرف بنجاح",
    errorAddingSupervisorAccount: "حدث خطأ أثناء إضافة المشرف",
    supervisorsAndStudents: "المشرفين والطلاب",
    supervisorsAndStudentsManagement: "إدارة المشرفين الأكاديميين والطلاب",
    noSupervisorsYet: "لا يوجد مشرفين حالياً",
    startByAddingSupervisors: "ابدأ بإضافة مشرفين جدد",
    projectsManagement: "إدارة المشاريع",

    // Notifications, Departments, and Reports
    nothingToShow: "لا يوجد شيء لعرضه",
    departmentsManagement: "إدارة الأقسام",
    addDepartment: "إضافة قسم",
    editDepartment: "تعديل القسم",
    deleteDepartment: "حذف القسم",
    departmentCode: "كود القسم",
    departmentNameAr: "الاسم بالعربي",
    departmentNameEn: "الاسم بالإنجليزي",
    departmentDescription: "وصف القسم",
    departmentActive: "القسم نشط",
    departmentInactive: "القسم معطل",
    noDepartments: "لا توجد أقسام",
    departmentAddedSuccessfully: "تم إضافة القسم بنجاح",
    departmentUpdatedSuccessfully: "تم تحديث القسم بنجاح",
    departmentDeletedSuccessfully: "تم حذف القسم بنجاح",
    errorAddingDepartment: "حدث خطأ أثناء إضافة القسم",
    errorUpdatingDepartment: "حدث خطأ أثناء تحديث القسم",
    errorDeletingDepartment: "حدث خطأ أثناء حذف القسم",
    confirmDeleteDepartment: "هل أنت متأكد من حذف هذا القسم؟",
    addDepartmentDescription: "إضافة وتعديل الأقسام الأكاديمية",
    canStudentsRegister: "يمكن للطلاب التسجيل في هذا القسم",
    reportsAndStatistics: "التقارير والإحصائيات",
    performanceReports: "إحصائيات وتقارير الأداء",
    generateReport: "تحميل التقرير",
    completionRate: "معدل الإنجاز",
    completionRateDescription: "نسبة المشاريع المكتملة من الإجمالي",
    averageProjectsPerSupervisor: "متوسط المشاريع لكل مشرف",
    averageProjectsDescription: "عدد المشاريع المخصصة لكل مشرف",
    completedProjects: "المشاريع المكتملة",
    pendingProjects: "المشاريع المعلقة",
    totalSupervisors: "عدد المشرفين",
    reportDate: "تاريخ التقرير",
    generalStatistics: "إحصائيات عامة",
    reportInformation: "معلومات التقرير",
    additionalProjectDetails: "تفاصيل إضافية حول المشاريع",
    inactive: "معطل",
    enabled: "مفعل",
    disabled: "معطل",
  },
  en: {
    // Common
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    submit: "Submit",
    search: "Search",
    filter: "Filter",
    close: "Close",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    actions: "Actions",
    view: "View",
    download: "Download",
    upload: "Upload",
    send: "Send",
    back: "Back",
    next: "Next",
    previous: "Previous",
    select: "Select",
    selectAll: "Select All",
    clear: "Clear",
    reset: "Reset",
    apply: "Apply",
    create: "Create",
    update: "Update",
    remove: "Remove",

    // Roles
    student: "Student",
    supervisor: "Supervisor",
    coordinator: "Coordinator",
    admin: "Admin",

    // Sidebar Navigation
    dashboard: "Dashboard",
    myProject: "My Project",
    tasks: "Tasks",
    meetings: "Meetings",
    files: "Files",
    announcements: "Announcements",
    discussions: "Discussions",
    messages: "Messages",
    grades: "Grades",
    notifications: "Notifications",
    settings: "Settings",
    logout: "Logout",
    profile: "Profile",
    projects: "Projects",
    students: "Students",
    supervisors: "Supervisors",
    reports: "Reports",
    archive: "Archive",
    assignSupervisors: "Assign Supervisors",
    projectIdeas: "Project Ideas",
    evaluations: "Evaluations",
    tasksAndEvaluation: "Tasks and Evaluation",

    // Platform
    platformTitle: "Projects Platform",
    graduationProjectsPlatform: "Graduation Projects Platform",
    mainMenu: "Main Menu",
    mainNavDescription: "Main navigation menu to access all system sections",

    // Auth Pages
    login: "Login",
    register: "Register",
    forgotPassword: "Forgot Password?",
    resetPassword: "Reset Password",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    name: "Name",
    phone: "Phone",
    studentId: "Student ID",
    employeeId: "Employee ID",
    department: "Department",
    role: "Role",
    loginButton: "Login",
    loggingIn: "Logging in...",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    invalidCredentials: "Invalid email or password",

    // Dashboard
    welcome: "Welcome",
    welcomeBack: "Welcome back",
    overviewText: "Here's an overview of your graduation project",
    supervisorOverview: "Overview of projects you supervise",
    coordinatorOverview: "Overview of all projects",
    totalTasks: "Total Tasks",
    completedTasks: "Completed Tasks",
    upcomingMeetings: "Upcoming Meetings",
    projectProgress: "Project Progress",
    recentTasks: "Recent Tasks",
    recentNotifications: "Recent Notifications",
    latestUpdates: "Latest Updates",
    noTasksYet: "No tasks yet",
    noDataFound: "User data not found",
    errorLoadingData: "Error loading data",
    errorOccurred: "An error occurred",
    welcomeToplatform: "Welcome to the Platform",
    startByAddingProject: "Start by adding your project and tracking tasks",

    // Project Page
    projectDetails: "Your graduation project details",
    myProjectDetails: "My Project Details",
    submitProjectIdea: "Submit Project Idea",
    submittedProjectIdeas: "Submitted Project Ideas",
    projectIdeasStatus: "Status of your submitted project ideas",
    submissionDate: "Submission Date",
    approved: "Approved",
    rejected: "Rejected",
    underReview: "Under Review",
    noProjectAssigned: "No project assigned yet",
    projectSubmittedUnderReview:
      "Project idea has been submitted and is under review. You will be notified of the decision soon.",
    submitOrWait: "Submit a project idea or wait for project assignment from the academic coordinator",
    active: "Active",
    completed: "Completed",
    pending: "Pending",
    inProgress: "In Progress",
    startDate: "Start Date",
    endDate: "End Date",
    expectedDeliveryDate: "Expected Delivery Date",
    notSpecified: "Not Specified",
    tasksAndAssignments: "Tasks and Assignments",
    discussionForum: "Discussion Forum",
    evaluationsAndResults: "Evaluations and Results",
    supervisorInfo: "Project supervisor information",
    contactSupervisor: "Contact Supervisor",
    projectObjectives: "Project Objectives",
    noObjectivesYet: "No objectives set yet",
    projectTitle: "Project Title",
    projectDescription: "Project Description",
    projectStatus: "Project Status",
    projectType: "Project Type",

    // Tasks
    taskTitle: "Task Title",
    taskDescription: "Task Description",
    taskStatus: "Task Status",
    taskPriority: "Task Priority",
    dueDate: "Due Date",
    assignedTo: "Assigned To",
    assignedBy: "Assigned By",
    new: "New",
    high: "High",
    medium: "Medium",
    low: "Low",
    urgent: "Urgent",
    addTask: "Add Task",
    editTask: "Edit Task",
    deleteTask: "Delete Task",
    completeTask: "Complete Task",
    markAsComplete: "Mark as Complete",
    markAsIncomplete: "Mark as Incomplete",

    // Meetings
    meetingTitle: "Meeting Title",
    meetingDescription: "Meeting Description",
    meetingDate: "Meeting Date",
    meetingTime: "Meeting Time",
    meetingLocation: "Meeting Location",
    meetingLink: "Meeting Link",
    meetingStatus: "Meeting Status",
    scheduled: "Scheduled",
    canceled: "Canceled",
    addMeeting: "Add Meeting",
    editMeeting: "Edit Meeting",
    deleteMeeting: "Delete Meeting",
    joinMeeting: "Join Meeting",
    scheduleMeeting: "Schedule Meeting",
    noMeetingsYet: "No meetings yet",
    upcomingMeeting: "Upcoming Meeting",
    pastMeeting: "Past Meeting",
    requestMeeting: "Request Meeting",
    meetingNotes: "Meeting Notes",
    date: "Date",
    time: "Time",
    meetingRequests: "Meeting Requests",
    submittedOn: "Submitted on",
    timeRange: "From 8 AM to 8 PM",
    meetingsBetweenHours: "Meetings must be between 8 AM and 8 PM",
    fieldRequired: "Please fill all required fields",
    savedSuccessfully: "Saved successfully",
    errorMessage: "An error occurred, please try again",

    // Archive
    restoreProject: "Restore Project",
    archived: "Archived",
    archivedProjects: "Archived Projects",
    noArchivedProjects: "No archived projects",
    archivedProjectsDescription: "Archived projects will appear here",
    projectRestoredSuccessfully: "Project restored successfully",
    errorRestoringProject: "Error restoring project",

    // Projects
    allProjects: "All Projects",
    approveProjects: "Approve Projects",
    addProject: "Add Project",
    editProject: "Edit Project",
    deleteProject: "Delete Project",
    viewDetails: "View Details",
    projectProposalDetails: "Project Proposal Details",
    acceptProject: "Accept Project",
    rejectProject: "Reject Project",
    suspendProject: "Suspend Project",
    archiveProject: "Archive Project",
    projectApprovedSuccessfully: "Project approved successfully",
    projectRejected: "Project rejected",
    projectSuspended: "Project suspended",
    projectArchived: "Project archived",
    errorApprovingProject: "Error approving project",
    errorRejectingProject: "Error rejecting project",
    errorSuspendingProject: "Error suspending project",
    errorArchivingProject: "Error archiving project",
    projectAddedSuccessfully: "Project added successfully",
    projectUpdatedSuccessfully: "Project updated successfully",
    projectDeletedSuccessfully: "Project deleted",
    errorAddingProject: "Error adding project",
    errorUpdatingProject: "Error updating project",
    errorDeletingProject: "Error deleting project",
    errorLoadingProjects: "Error loading projects",
    suspended: "Suspended",
    progress: "Progress",
    notAssigned: "Not Assigned",
    objectives: "Objectives",
    confirmDelete: "Are you sure you want to delete this project?",
    teamManagement: "Team Management",
    teamMembers: "Team Members",
    addStudentToProject: "Add Student to Project",
    removeStudent: "Remove Student",
    studentAddedSuccessfully: "Student added to project successfully",
    studentRemovedSuccessfully: "Student removed from project",
    studentAlreadyHasProject: "This student already has a project",
    errorAddingStudent: "Error adding student",
    errorRemovingStudent: "Error removing student",
    errorLoadingTeamMembers: "Error loading team members",
    pleaseSelectStudent: "Please select a student",
    ideaDataLoaded: "Approved idea data loaded, please select a supervisor",
    errorLoadingIdeaData: "Error loading idea data",

    // Students
    studentsManagement: "Students Management",
    assignSupervisorsDescription: "Assign supervisors to students and track their status",
    addNewStudent: "Add New Student",
    totalStudents: "Total Students",
    studentsWithoutSupervisor: "Students Without Supervisor",
    studentsWithSupervisor: "Students With Supervisor",
    noStudentsYet: "No students yet",
    studentsWillAppearHere: "Students will appear here after registration",
    studentsList: "Students List",
    allRegisteredStudents: "All registered students in the system",
    assigned: "Assigned",
    withoutSupervisor: "Without Supervisor",
    changeSupervisor: "Change Supervisor",
    assignSupervisor: "Assign Supervisor",
    selectAppropiateSupervisor: "Select the appropriate supervisor for the student",
    selectedSupervisor: "Selected Supervisor",
    currentStudentCount: "Current Student Count",
    supervisorAssignedSuccessfully: "Supervisor assigned successfully",
    errorAssigningSupervisor: "Error assigning supervisor",
    pleaseSelectSupervisor: "Please select a supervisor",
    fullName: "Full Name",
    enterFullName: "Enter full name",
    enterEmail: "Enter email",
    enterPassword: "Enter password",
    universityId: "University ID",
    example: "Example",
    selectDepartment: "Select Department",
    noDepartmentsAvailable: "No departments available",
    addDepartmentsFromSettings: "Please add departments from the departments management page",
    selectedDepartment: "Selected Department",
    phoneNumber: "Phone Number",
    studentAddedSuccessfully: "Student added successfully",
    emailAlreadyInUse: "Email already in use",
    errorAddingStudentAccount: "Error adding student",
    assign: "Assign",
    addStudent: "Add Student",
    enterStudentData: "Enter student data to create a new account",

    // Discussions
    discussionForum: "Discussion Forum",
    shareIdeasWithTeam: "Share ideas and questions with your team",
    newDiscussion: "New Discussion",
    createNewDiscussion: "Create New Discussion",
    discussionTitle: "Discussion Title",
    enterDiscussionTitle: "Enter discussion title",
    discussionContent: "Discussion Content",
    explainDiscussionInDetail: "Explain the discussion topic in detail",
    tags: "Tags",
    optional: "Optional",
    tagsExample: "Example: technical, report, review (separate with comma)",
    separateTagsWithComma: "Separate tags with comma",
    createDiscussion: "Create Discussion",
    discussionCreatedSuccessfully: "Discussion created successfully",
    errorCreatingDiscussion: "Error creating discussion",
    errorFetchingDiscussions: "Error fetching discussions",
    all: "All",
    open: "Open",
    closed: "Closed",
    noDiscussions: "No Discussions",
    noDiscussionsYet: "No discussions created yet. Start by creating a new discussion.",
    pinned: "Pinned",
    reply: "Reply",
    discussionNotFound: "Discussion not found",
    noProject: "No Project",
    mustBeInProjectForDiscussions: "You must be enrolled in a project to participate in discussions",
    mustBeInProjectToCreateDiscussion: "You must have a project to create a discussion",
    fewMinutesAgo: "A few minutes ago",
    hoursAgo: "{hours} hours ago",
    oneDayAgo: "One day ago",

    // Announcements
    announcements: "Announcements",
    announcementsManagement: "Manage and publish general announcements for all users",
    newAnnouncement: "New Announcement",
    publishNewAnnouncement: "Publish New General Announcement",
    announcementTitle: "Announcement Title",
    enterAnnouncementTitle: "Enter announcement title",
    announcementContent: "Announcement Content",
    enterAnnouncementContent: "Enter announcement content",
    announcementScope: "Announcement Scope",
    selectAnnouncementScope: "Select announcement scope",
    singleSemesterProjects: "Single Semester Projects",
    twoSemestersProjects: "Two Semesters Projects",
    other: "Other",
    selectTargetCategory: "Select the target category for the announcement",
    pinAnnouncement: "Pin Announcement",
    announcementWillAppearOnTop: "The announcement will appear at the top of the list",
    publishAnnouncement: "Publish Announcement",
    announcementPublishedSuccessfully: "Announcement published successfully",
    errorPublishingAnnouncement: "Error publishing announcement",
    noAnnouncements: "No Announcements",
    noAnnouncementsYet: "No announcements published yet. Start by publishing a new general announcement.",
    confirmDeleteAnnouncement: "Are you sure you want to delete this announcement?",
    announcementDeletedSuccessfully: "Announcement deleted successfully",
    errorDeletingAnnouncement: "Error deleting announcement",
    unpin: "Unpin",
    pin: "Pin",
    unpinned: "Unpinned",
    announcementPinned: "Announcement pinned",

    // General
    fillAllRequiredFields: "Please fill all required fields",
    required: "Required",

    // Common Actions
    total: "Total",
    noContent: "No content",
    viewAll: "View All",
    typeMessage: "Type your message here...",
    attachedFiles: "Attached Files",
    attachFile: "Must attach file or write text",
    feedback: "Feedback",

    // Task & Grading
    taskSubmitted: "Submitted",
    taskGraded: "Graded",
    grade: "Grade",
    weight: "Weight",
    maxGrade: "Max Grade",
    evaluationFeedback: "Evaluation Feedback",
    noGradesYet: "No grades yet",
    errorLoadingTasks: "Error loading tasks",
    userNotFound: "User not found",
    newTaskAssigned: "New Task",

    // Project & Students
    activeProjects: "Active Projects",
    projectsCount: "Projects Count",
    noStudentsWithoutSupervisors: "No students without supervisors",
    calendar: "Calendar",
    departments: "Departments Management",
    selectProject: "Select Project",
    chooseProject: "Choose Project",

    // UI Text
    noProjectsAvailable: "No projects available",

    // Archive
    selectProjectDescription: "Select archived project to restore",

    // Supervisors
    addSupervisor: "Add Supervisor",
    addNewSupervisor: "Add New Supervisor",
    enterSupervisorData: "Enter supervisor data",
    jobNumber: "Job Number",
    enterJobNumber: "Enter job number",
    supervisorAddedSuccessfully: "Supervisor added successfully",
    errorAddingSupervisorAccount: "Error adding supervisor",
    supervisorsAndStudents: "Supervisors and Students",
    supervisorsAndStudentsManagement: "Academic Supervisors and Students Management",
    noSupervisorsYet: "No supervisors yet",
    startByAddingSupervisors: "Start by adding new supervisors",
    projectsManagement: "Projects Management",

    // Notifications, Departments, and Reports
    nothingToShow: "Nothing to show",
    departmentsManagement: "Departments Management",
    addDepartment: "Add Department",
    editDepartment: "Edit Department",
    deleteDepartment: "Delete Department",
    departmentCode: "Department Code",
    departmentNameAr: "Arabic Name",
    departmentNameEn: "English Name",
    departmentDescription: "Department Description",
    departmentActive: "Department Active",
    departmentInactive: "Department Inactive",
    noDepartments: "No departments",
    departmentAddedSuccessfully: "Department added successfully",
    departmentUpdatedSuccessfully: "Department updated successfully",
    departmentDeletedSuccessfully: "Department deleted successfully",
    errorAddingDepartment: "Error adding department",
    errorUpdatingDepartment: "Error updating department",
    errorDeletingDepartment: "Error deleting department",
    confirmDeleteDepartment: "Are you sure you want to delete this department?",
    addDepartmentDescription: "Add and edit academic departments",
    canStudentsRegister: "Students can register in this department",
    reportsAndStatistics: "Reports and Statistics",
    performanceReports: "Performance reports and statistics",
    generateReport: "Download Report",
    completionRate: "Completion Rate",
    completionRateDescription: "Percentage of completed projects out of total",
    averageProjectsPerSupervisor: "Average Projects per Supervisor",
    averageProjectsDescription: "Number of projects assigned to each supervisor",
    completedProjects: "Completed Projects",
    pendingProjects: "Pending Projects",
    totalSupervisors: "Total Supervisors",
    reportDate: "Report Date",
    generalStatistics: "General Statistics",
    reportInformation: "Report Information",
    additionalProjectDetails: "Additional project details",
    inactive: "Inactive",
    enabled: "Enabled",
    disabled: "Disabled",
  },
}
